# Ip adresses and port of hub servers
# Set the port in 'config.yml' in your ServerSelectorX folder
addresses:
- 'localhost:9782'

# Set this to the name of this server EXACTLY as specified in the bungeecord config.
server-name: ''

# How often the connector plugin sends placeholders (4 means once every 4 seconds)
# You need to restart your server completely after changing this, /ssxc reload is not enough.
send-interval: 4

log-ping-fail: true

# don't touch this option unless you know you need to
password: "a"